### PR TITLE
Adds curved_connected_roads map.

### LINKED ISSUE #47: Map Request: Connected Curved Road With Extended Approach, Middle, and Exit
This is a second iteration of #25. We'd like to connect the two curved roads and extended the approach  / exit roads 300m.

connected_curved_road_extended

Note the 300m of approach / exit stretches of straight road on both sides.
We can name this "**double_curved_road**".

### PR DESCRIPTION
**Pull request by francocipollone**
# 🎉 New feature

Closes #47 

## Summary
 - Adds template for curved connected roads
    - image
 - Resource added using:
   - `EXIT_ROAD_LENGTH=300`
   -  `MIDDLE_ROAD_LENGTH=300`
   - `RADIUS=12`
   - `WIDTH=3.5`

## Test it
```
EXIT_ROAD_LENGTH=300 MIDDLE_ROAD_LENGTH=300 RADIUS=12 empy3 templates/curved_connected_roads.xml.em > generated_file.xodr
```

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by francocipollone** [comment]
Just noticed that the issue says:
```
We can name this "double_curved_road".
```

I named it `curved_connected_roads`

I can adapt names in a follow-up pr if you want. If so let me know if you want to keep the previous version of the map (where both double curves aren't connected.)

**Comment by liangfok** [comment]
Update: This continues to undergo testing by our downstream users.

**Comment by liangfok** [comment]
Question: 
10cm_gap_question

**Comment by francocipollone** [comment]
> Question: 

I've found no gap neither in OpenDRIVE nor maliput level. The only way you found such a gap there is if you are working with a linear tolerance of 5 cm or so.

**Comment by liangfok** [comment]
Ah, I see [this kLinearTolerance documentation](https://maliput.readthedocs.io/en/latest/html/deps/maliput_malidrive/html/group__road__geometry__configuration__builder__keys.html#gac6e403db72f1c6cea48836ea7754e3de) says "When max_linear_tolerance isn't also set then "5e-2" (malidrive::constants::kLinearTolerance) is used." That would explain the 10cm gap.

**Comment by francocipollone** [comment]
> Ah, I see [this kLinearTolerance documentation](https://maliput.readthedocs.io/en/latest/html/deps/maliput_malidrive/html/group__road__geometry__configuration__builder__keys.html#gac6e403db72f1c6cea48836ea7754e3de) says "When max_linear_tolerance isn't also set then "5e-2" (malidrive::constants::kLinearTolerance) is used." That would explain the 10cm gap.

I just re-checked the implementation: The relationship would be: if you set a linear tolerance of 5 cm you will get a gap of 2.5m (the gap will not affect as it is below linear tolerance.)

So In order to have a gap of 10 cm you need to set a linear tolerance of 20 cm, which is quite large, so I would check downstream (your tool) what linear tolerance is passing to the builder.

**Comment by liangfok** [comment]
I confirmed that our downstream tooling loads this map with a linear tolerance of 0.05m (5cm). This was determined by calling `road_network_->road_geometry()->linear_tolerance()` after loading the road network.

**Review by liangfok — APPROVED** [review]
LGTM

**Pull request merged**
