### PR TITLE
Adds curved road map.

### PR DESCRIPTION
**Pull request by francocipollone**
# 🎉 New feature

## Summary

Description:
 - 2 curved non-connected roads

Options:
 - `WIDTH`: Width of the lanes(default 3.5m).
 - `RADIUS`: Radius of the curved section(default 12m).
 - `LENGTH_STRAIGHT`: Length of the straight section(default 20m).
 - `GAP`: Distance between roads(default 1m).
 - `X_OFFSET`: X offset with respect to the origin.
 - `Y_OFFSET`: Y offset with respect to the origin.

## Test it
```sh
LENGTH_STRAIGHT=25 RADIUS=15 GAP=5 empy3 templates/curved_road.xml.em > generated_file.xodr
```

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

### CODE REVIEW

**Comment by francocipollone** [comment]
Here there is the generated xodr file: https://github.com/maliput/maliput_xodr/blob/francocipollone/curved_road/resources/curved_road/curved_road_default.xodr

**Comment by liangfok** [comment]
Thanks for creating this. I'll test it ASAP.

**Comment by liangfok** [comment]
Test completed and passed. This can be merged.

**Review by liangfok — DISMISSED** [review]
LGTM

**Review by agalbachicar — DISMISSED** [review]
LGTM

**Pull request merged**
