### PR TITLE
Circle map amendments

### PR DESCRIPTION
**Pull request by agalbachicar**
# 🦟 Bug fix

Part of #61 
Goes on top of #62 

## Summary
Implements changes requested [here](https://github.com/maliput/maliput_xodr/issues/61#issuecomment-1893660703).

https://github.com/maliput/maliput_xodr/assets/3825465/a83543ac-50db-4e17-959a-5720263809a6

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by liangfok** [comment]
To be consistent with existing naming conventions, let's rename:
```
circle_6_5m_inner_radius_inner_lane_4_3_m_outer_lane_5_3_m_lanes.xodr
```
to be:
```
circle_6_5m_inner_radius_inner_lane_4_3m_outer_lane_5_3m_lanes.xodr
```
Note the removal of "_" before the "m."

**Comment by liangfok** [comment]
Actually, because "inner_radius_inner_lane" might be difficult to parse, let's use the following, which I think is easier to understand:

```
circle_6_5m_inner_radius_4_3m_inner_lane_5_3m_outer_lane.xodr
```

**Comment by agalbachicar** [comment]
Besides the change of name, is there anything else required? Is the map content good enough?

**Comment by liangfok** [comment]
Initial visual inspection looks good. It is currently undergoing downstream testing. Will provide an update once complete.

**Comment by agalbachicar** [comment]
> Actually, because "inner_radius_inner_lane" might be difficult to parse, let's use the following, which I think is easier to understand:

> circle_6_5m_inner_radius_4_3m_inner_lane_5_3m_outer_lane.xodr

Done in [12e1ec3](https://github.com/maliput/maliput_xodr/pull/64/commits/12e1ec394a90ebde3c8d136ab40c1a64d7bb05c0)

**Review by francocipollone — APPROVED** [review]
LGTM! Thanks for the changes!

**Comment by francocipollone** [comment]
Going in. If there is further amendments to do let's tackle them in the parent PR #62

**Pull request merged**
